import Head from 'next/head'

import ProfilesList from '@/components/profilesList/ProfilesList'

export default function Profiles() {
   return (
      <>
         <Head>
         <title>Profiles</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
         </Head>
         <ProfilesList/>
      </>
   )
}